project:
  type: website
  output-dir: docs

website:
  title: "Thiago Scot"
  description: "Personal website of Thiago Scot"
  #site-url: https://ddimmery.com
  repo-url: https://github.com/thiagoscot/thiagoscot_website
  #google-analytics: "G-Y7YLFF5F90"
  open-graph: true
  navbar:
    background: dark
    foreground: light
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual